#Title of the website
website_title: "Centural"

#Google Excell Chat Response Spreadsheet ID
chatbox_sheet_id: "1xAbPj6YgOWm2LzgrArirLceLfaJZEJ5D2pbo3WkR_x0"

#Google API Key
google_client_id: "682787828036-4g2eq0jk4csvk4lrkjbfm33682v7cptq.apps.googleusercontent.com"
google_api_key: "AIzaSyBufUkPuFTjj1nGfAuJs_hk6qSTrPJVJMA"
